const admins = [
  {
    id: 1,
    avatar: "https://i.pravatar.cc/500?img=1",
    name: "John Doe",
    email: "johndoe@example.com",
    createdAt: "2024-12-01 08:45:23",
    status: true,
  },
  {
    id: 2,
    avatar: "https://i.pravatar.cc/500?img=2",
    name: "Jane Smith",
    email: "janesmith@example.com",
    createdAt: "2024-12-02 10:15:40",
    status: false,
  },
  {
    id: 3,
    avatar: "https://i.pravatar.cc/500?img=3",
    name: "Michael Brown",
    email: "michaelbrown@example.com",
    createdAt: "2024-12-03 12:30:15",
    status: true,
  },
  {
    id: 4,
    avatar: "https://i.pravatar.cc/500?img=4",
    name: "Emily Davis",
    email: "emilydavis@example.com",
    createdAt: "2024-12-04 14:45:55",
    status: false,
  },
  {
    id: 5,
    avatar: "https://i.pravatar.cc/500?img=5",
    name: "Chris Wilson",
    email: "chriswilson@example.com",
    createdAt: "2024-12-05 16:10:30",
    status: true,
  },
  {
    id: 6,
    avatar: "https://i.pravatar.cc/500?img=6",
    name: "Sarah Johnson",
    email: "sarahjohnson@example.com",
    createdAt: "2024-12-06 17:25:10",
    status: false,
  },
  {
    id: 7,
    avatar: "https://i.pravatar.cc/500?img=7",
    name: "David Clark",
    email: "davidclark@example.com",
    createdAt: "2024-12-07 18:50:45",
    status: true,
  },
  {
    id: 8,
    avatar: "https://i.pravatar.cc/500?img=8",
    name: "Sophia Martinez",
    email: "sophiamartinez@example.com",
    createdAt: "2024-12-08 20:05:20",
    status: false,
  },
  {
    id: 9,
    avatar: "https://i.pravatar.cc/500?img=9",
    name: "Daniel White",
    email: "danielwhite@example.com",
    createdAt: "2024-12-09 21:30:05",
    status: true,
  },
  {
    id: 10,
    avatar: "https://i.pravatar.cc/500?img=10",
    name: "Olivia Harris",
    email: "oliviaharris@example.com",
    createdAt: "2024-12-10 22:45:50",
    status: false,
  },
];

const managers = [
  {
    id: 1,
    avatar: "https://i.pravatar.cc/500?img=11",
    name: "Liam Carter",
    email: "liamcarter@example.com",
    createdAt: "2024-12-11 08:45:23",
    status: true,
  },
  {
    id: 2,
    avatar: "https://i.pravatar.cc/500?img=12",
    name: "Ava Brooks",
    email: "avabrooks@example.com",
    createdAt: "2024-12-11 10:15:40",
    status: false,
  },
  {
    id: 3,
    avatar: "https://i.pravatar.cc/500?img=13",
    name: "Noah Evans",
    email: "noahevans@example.com",
    createdAt: "2024-12-11 12:30:15",
    status: true,
  },
  {
    id: 4,
    avatar: "https://i.pravatar.cc/500?img=14",
    name: "Mia Scott",
    email: "miascott@example.com",
    createdAt: "2024-12-11 14:45:55",
    status: false,
  },
  {
    id: 5,
    avatar: "https://i.pravatar.cc/500?img=15",
    name: "James King",
    email: "jamesking@example.com",
    createdAt: "2024-12-11 16:10:30",
    status: true,
  },
  {
    id: 6,
    avatar: "https://i.pravatar.cc/500?img=16",
    name: "Isabella Wright",
    email: "isabellawright@example.com",
    createdAt: "2024-12-11 17:25:10",
    status: false,
  },
  {
    id: 7,
    avatar: "https://i.pravatar.cc/500?img=17",
    name: "Ethan Hall",
    email: "ethanhall@example.com",
    createdAt: "2024-12-11 18:50:45",
    status: true,
  },
  {
    id: 8,
    avatar: "https://i.pravatar.cc/500?img=18",
    name: "Charlotte Turner",
    email: "charlotteturner@example.com",
    createdAt: "2024-12-11 20:05:20",
    status: false,
  },
  {
    id: 9,
    avatar: "https://i.pravatar.cc/500?img=19",
    name: "William Morgan",
    email: "williammorgan@example.com",
    createdAt: "2024-12-11 21:30:05",
    status: true,
  },
  {
    id: 10,
    avatar: "https://i.pravatar.cc/500?img=20",
    name: "Sophia Perez",
    email: "sophiaperez@example.com",
    createdAt: "2024-12-11 22:45:50",
    status: false,
  },
];

const nurses = [
  {
    id: 1,
    avatar: "https://i.pravatar.cc/500?img=21",
    name: "Oliver Sanders",
    email: "oliversanders@example.com",
    createdAt: "2024-12-12 08:15:23",
    status: true,
  },
  {
    id: 2,
    avatar: "https://i.pravatar.cc/500?img=22",
    name: "Amelia Cook",
    email: "ameliacook@example.com",
    createdAt: "2024-12-12 09:25:40",
    status: false,
  },
  {
    id: 3,
    avatar: "https://i.pravatar.cc/500?img=23",
    name: "Lucas Hughes",
    email: "lucashughes@example.com",
    createdAt: "2024-12-12 10:45:15",
    status: true,
  },
  {
    id: 4,
    avatar: "https://i.pravatar.cc/500?img=24",
    name: "Harper Bell",
    email: "harperbell@example.com",
    createdAt: "2024-12-12 11:55:55",
    status: false,
  },
  {
    id: 5,
    avatar: "https://i.pravatar.cc/500?img=25",
    name: "Benjamin Reed",
    email: "benjaminreed@example.com",
    createdAt: "2024-12-12 13:10:30",
    status: true,
  },
  {
    id: 6,
    avatar: "https://i.pravatar.cc/500?img=26",
    name: "Ella Gray",
    email: "ellagray@example.com",
    createdAt: "2024-12-12 14:20:10",
    status: false,
  },
  {
    id: 7,
    avatar: "https://i.pravatar.cc/500?img=27",
    name: "Henry Adams",
    email: "henryadams@example.com",
    createdAt: "2024-12-12 15:40:45",
    status: true,
  },
  {
    id: 8,
    avatar: "https://i.pravatar.cc/500?img=28",
    name: "Chloe Cooper",
    email: "chloecooper@example.com",
    createdAt: "2024-12-12 16:55:20",
    status: false,
  },
  {
    id: 9,
    avatar: "https://i.pravatar.cc/500?img=29",
    name: "Alexander Mitchell",
    email: "alexandermitchell@example.com",
    createdAt: "2024-12-12 18:10:05",
    status: true,
  },
  {
    id: 10,
    avatar: "https://i.pravatar.cc/500?img=30",
    name: "Lily Parker",
    email: "lilyparker@example.com",
    createdAt: "2024-12-12 19:25:50",
    status: false,
  },
];

const doctors = [
  {
    id: 1,
    avatar: "https://i.pravatar.cc/500?img=31",
    name: { en: "Dr. Emma Collins", ar: "الدكتورة إيما كولينز" },
    email: "emmacollins@example.com",
    createdAt: "2024-12-13 08:10:45",
    status: true,
    designation: { en: "Cardiologist", ar: "طبيبة قلب" },
  },
  {
    id: 2,
    avatar: "https://i.pravatar.cc/500?img=32",
    name: { en: "Dr. Jack Murphy", ar: "الدكتور جاك مورفي" },
    email: "jackmurphy@example.com",
    createdAt: "2024-12-13 09:20:30",
    status: false,
    designation: { en: "Neurologist", ar: "طبيب أعصاب" },
  },
  {
    id: 3,
    avatar: "https://i.pravatar.cc/500?img=33",
    name: { en: "Dr. Sophia Jenkins", ar: "الدكتورة صوفيا جينكينز" },
    email: "sophiajenkins@example.com",
    createdAt: "2024-12-13 10:35:12",
    status: true,
    designation: { en: "Pediatrician", ar: "طبيبة أطفال" },
  },
  {
    id: 4,
    avatar: "https://i.pravatar.cc/500?img=34",
    name: { en: "Dr. Logan Barnes", ar: "الدكتور لوغان بارنز" },
    email: "loganbarnes@example.com",
    createdAt: "2024-12-13 11:50:55",
    status: false,
    designation: { en: "Dermatologist", ar: "طبيب أمراض جلدية" },
  },
  {
    id: 5,
    avatar: "https://i.pravatar.cc/500?img=35",
    name: { en: "Dr. Grace Foster", ar: "الدكتورة جريس فوستر" },
    email: "gracefoster@example.com",
    createdAt: "2024-12-13 13:05:40",
    status: true,
    designation: { en: "Orthopedic Surgeon", ar: "جراحة العظام" },
  },
  {
    id: 6,
    avatar: "https://i.pravatar.cc/500?img=36",
    name: { en: "Dr. Mason Howard", ar: "الدكتور ميسون هوارد" },
    email: "masonhoward@example.com",
    createdAt: "2024-12-13 14:20:18",
    status: false,
    designation: { en: "Psychiatrist", ar: "طبيب نفسي" },
  },
  {
    id: 7,
    avatar: "https://i.pravatar.cc/500?img=37",
    name: { en: "Dr. Hannah Russell", ar: "الدكتورة هانا راسل" },
    email: "hannahrussell@example.com",
    createdAt: "2024-12-13 15:40:25",
    status: true,
    designation: { en: "Gynecologist", ar: "طبيبة نساء وولادة" },
  },
  {
    id: 8,
    avatar: "https://i.pravatar.cc/500?img=38",
    name: { en: "Dr. Ethan Brooks", ar: "الدكتور إيثان بروكس" },
    email: "ethanbrooks@example.com",
    createdAt: "2024-12-13 16:55:09",
    status: false,
    designation: { en: "Oncologist", ar: "طبيب أورام" },
  },
  {
    id: 9,
    avatar: "https://i.pravatar.cc/500?img=39",
    name: { en: "Dr. Scarlett Edwards", ar: "الدكتورة سكارليت إدواردز" },
    email: "scarlettedwards@example.com",
    createdAt: "2024-12-13 18:15:35",
    status: true,
    designation: { en: "Radiologist", ar: "طبيبة أشعة" },
  },
  {
    id: 10,
    avatar: "https://i.pravatar.cc/500?img=40",
    name: { en: "Dr. Henry Bennett", ar: "الدكتور هنري بينيت" },
    email: "henrybennett@example.com",
    createdAt: "2024-12-13 19:30:50",
    status: false,
    designation: { en: "Anesthesiologist", ar: "طبيب تخدير" },
  },
];


const devices = [
  {
    id: 1,
    deviceMacId: "00:1A:2B:3C:4D:5E",
    hospital: "City Hospital",
    location: "Building A, Floor 3, Room 15, North Wing, New York, Manhattan",
    createdAt: "2024-12-13 08:10:45",
    status: true,
  },
  {
    id: 2,
    deviceMacId: "11:22:33:44:55:66",
    hospital: "Green Valley Clinic",
    location: "Building B, Floor 2, Room 8, South Wing, California, Los Angeles",
    createdAt: "2024-12-13 09:15:30",
    status: false,
  },
  {
    id: 3,
    deviceMacId: "AA:BB:CC:DD:EE:FF",
    hospital: "Blue Cross Medical",
    location: "Building C, Floor 1, Room 5, East Wing, Illinois, Chicago",
    createdAt: "2024-12-13 10:05:55",
    status: true,
  },
  {
    id: 4,
    deviceMacId: "77:88:99:AA:BB:CC",
    hospital: "Sunrise Healthcare",
    location: "Building D, Floor 4, Room 12, West Wing, Texas, Houston",
    createdAt: "2024-12-13 11:20:40",
    status: false,
  },
  {
    id: 5,
    deviceMacId: "FF:EE:DD:CC:BB:AA",
    hospital: "Wellness Center",
    location: "Building E, Floor 2, Room 10, Central Wing, Arizona, Phoenix",
    createdAt: "2024-12-13 12:45:25",
    status: true,
  },
  {
    id: 6,
    deviceMacId: "12:34:56:78:9A:BC",
    hospital: "LifeCare Hospital",
    location: "Building F, Floor 3, Room 7, North Wing, Pennsylvania, Philadelphia",
    createdAt: "2024-12-13 14:10:30",
    status: false,
  },
  {
    id: 7,
    deviceMacId: "1A:2B:3C:4D:5E:6F",
    hospital: "Global Health Clinic",
    location: "Building G, Floor 1, Room 3, South Wing, California, San Diego",
    createdAt: "2024-12-13 15:25:15",
    status: true,
  },
  {
    id: 8,
    deviceMacId: "6F:5E:4D:3C:2B:1A",
    hospital: "Pioneer Medical Center",
    location: "Building H, Floor 2, Room 6, East Wing, Texas, Dallas",
    createdAt: "2024-12-13 16:50:45",
    status: false,
  },
  {
    id: 9,
    deviceMacId: "98:76:54:32:10:BA",
    hospital: "St. Mary's Hospital",
    location: "Building I, Floor 3, Room 9, West Wing, California, San Francisco",
    createdAt: "2024-12-13 17:35:50",
    status: true,
  },
  {
    id: 10,
    deviceMacId: "23:45:67:89:AB:CD",
    hospital: "Prime Health Institute",
    location: "Building J, Floor 4, Room 4, Central Wing, Washington, Seattle",
    createdAt: "2024-12-13 19:20:10",
    status: false,
  },
];

const deviceLogs = [
  {
    id: 1,
    deviceMacId: "00:1A:2B:3C:4D:5E",
    hospital: "City Hospital",
    location: "Building A, Floor 3, Room 15, North Wing, New York, Manhattan",
    deviceType: "Patient Monitor",
    status: true,
    lastStatusChangeTime: "2024-12-13 08:30:00",
    changedBy: "Dr. Emma Collins",
  },
  {
    id: 2,
    deviceMacId: "11:22:33:44:55:66",
    hospital: "Green Valley Clinic",
    location: "Building B, Floor 2, Room 8, South Wing, California, Los Angeles",
    deviceType: "Ventilator",
    status: false,
    lastStatusChangeTime: "2024-12-13 09:20:45",
    changedBy: "Dr. Jack Murphy",
  },
  {
    id: 3,
    deviceMacId: "AA:BB:CC:DD:EE:FF",
    hospital: "Blue Cross Medical",
    location: "Building C, Floor 1, Room 5, East Wing, Illinois, Chicago",
    deviceType: "ECG Machine",
    status: true,
    lastStatusChangeTime: "2024-12-13 10:15:10",
    changedBy: "Dr. Sophia Jenkins",
  },
  {
    id: 4,
    deviceMacId: "77:88:99:AA:BB:CC",
    hospital: "Sunrise Healthcare",
    location: "Building D, Floor 4, Room 12, West Wing, Texas, Houston",
    deviceType: "Pulse Oximeter",
    status: false,
    lastStatusChangeTime: "2024-12-13 11:30:25",
    changedBy: "Dr. Logan Barnes",
  },
  {
    id: 5,
    deviceMacId: "FF:EE:DD:CC:BB:AA",
    hospital: "Wellness Center",
    location: "Building E, Floor 2, Room 10, Central Wing, Arizona, Phoenix",
    deviceType: "Defibrillator",
    status: true,
    lastStatusChangeTime: "2024-12-13 12:50:40",
    changedBy: "Dr. Grace Foster",
  },
  {
    id: 6,
    deviceMacId: "12:34:56:78:9A:BC",
    hospital: "LifeCare Hospital",
    location: "Building F, Floor 3, Room 7, North Wing, Pennsylvania, Philadelphia",
    deviceType: "Infusion Pump",
    status: false,
    lastStatusChangeTime: "2024-12-13 14:30:55",
    changedBy: "Dr. Mason Howard",
  },
  {
    id: 7,
    deviceMacId: "1A:2B:3C:4D:5E:6F",
    hospital: "Global Health Clinic",
    location: "Building G, Floor 1, Room 3, South Wing, California, San Diego",
    deviceType: "Ultrasound Machine",
    status: true,
    lastStatusChangeTime: "2024-12-13 15:40:10",
    changedBy: "Dr. Hannah Russell",
  },
  {
    id: 8,
    deviceMacId: "6F:5E:4D:3C:2B:1A",
    hospital: "Pioneer Medical Center",
    location: "Building H, Floor 2, Room 6, East Wing, Texas, Dallas",
    deviceType: "Thermometer",
    status: false,
    lastStatusChangeTime: "2024-12-13 16:55:25",
    changedBy: "Dr. Ethan Brooks",
  },
  {
    id: 9,
    deviceMacId: "98:76:54:32:10:BA",
    hospital: "St. Mary's Hospital",
    location: "Building I, Floor 3, Room 9, West Wing, California, San Francisco",
    deviceType: "Oxygen Cylinder",
    status: true,
    lastStatusChangeTime: "2024-12-13 17:40:35",
    changedBy: "Dr. Scarlett Edwards",
  },
  {
    id: 10,
    deviceMacId: "23:45:67:89:AB:CD",
    hospital: "Prime Health Institute",
    location: "Building J, Floor 4, Room 4, Central Wing, Washington, Seattle",
    deviceType: "Blood Pressure Monitor",
    status: false,
    lastStatusChangeTime: "2024-12-13 19:30:50",
    changedBy: "Dr. Henry Bennett",
  },
];

export { admins , managers , nurses , doctors , devices , deviceLogs };